In [2]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [3]:
cost_of_living = pd.read_excel("C:/Users/mayur/Downloads/fbc_data_2022 (2).xlsx",sheet_name = "Metro")
#loading the excel sheet in python

In [4]:
print(cost_of_living)
#analyze the data, look at the number of rows and columns. Correct the header name, row zero should be the header.

     Unnamed: 0  Unnamed: 1       Unnamed: 2 Unnamed: 3  Monthly Unnamed: 5  \
0       case_id  State abv.         Areaname     Family  Housing       Food
1          3172          TX  Abilene, TX MSA       1p0c      707    251.215
2          3172          TX  Abilene, TX MSA       1p1c      955     370.23
3          3172          TX  Abilene, TX MSA       1p2c      955    542.449
4          3172          TX  Abilene, TX MSA       1p3c     1285    723.651
...         ...         ...              ...        ...      ...        ...
6576       3829          AZ     Yuma, AZ MSA       2p0c      705    431.144
6577       3829          AZ     Yuma, AZ MSA       2p1c      927    536.602
6578       3829          AZ     Yuma, AZ MSA       2p2c      927    679.595
6579       3829          AZ     Yuma, AZ MSA       2p3c     1321    829.734
6580       3829          AZ     Yuma, AZ MSA       2p4c     1321     1015.4

          Unnamed: 6  Unnamed: 7          Unnamed: 8 Unnamed: 9  ...  \
0     Transportation  Healthcare  Other Necessities   Childcare  ...
1            846.898     449.123             347.199          0  ...
2            905.223      678.22             480.183    578.983  ...
3            971.822     907.318             542.585    978.568  ...
4            1064.56     1136.41             727.813    1101.52  ...
...              ...         ...                 ...        ...  ...
6576         1051.11      1123.4              411.67          0  ...
6577         1128.94     1403.96             530.321    691.616  ...
6578         1187.83     1684.53             582.133    1330.86  ...
6579         1280.26      1965.1             779.296    1527.54  ...
6580         1303.09     2245.66             846.568    1527.54  ...

     Unnamed: 15         Unnamed: 16 Unnamed: 17 Unnamed: 18 Unnamed: 19  \
0     Healthcare  Other Necessities    Childcare       Taxes       Total
1        5389.48             4166.39           0     4687.84     35905.1
2        8138.65              5762.2      6947.8      4689.7     52303.8
3        10887.8             6511.02     11742.8     4363.63     63136.5
4          13637             8733.76     13218.2     5737.31     78204.8
...          ...                 ...         ...         ...         ...
6576     13480.8             4940.04           0     6468.11     51135.9
6577     16847.6             6363.85     8299.39     8009.27     70630.6
6578     20214.4             6985.59     15970.3     8670.22     85373.6
6579     23581.2             9351.55     18330.5     10922.8      103358
6580       26948             10158.8     18330.5     10746.2      109857

                  Rankings Unnamed: 21       Unnamed: 22          Unnamed: 23  \
0     median_family_income      top100  top100_cost_rank  top100_med_aff_rank
1                  66485.1           0               NaN                  NaN
2                  66485.1           0               NaN                  NaN
3                  66485.1           0               NaN                  NaN
4                  66485.1           0               NaN                  NaN
...                    ...         ...               ...                  ...
6576               51688.4           0               NaN                  NaN
6577               51688.4           0               NaN                  NaN
6578               51688.4           0               NaN                  NaN
6579               51688.4           0               NaN                  NaN
6580               51688.4           0               NaN                  NaN

                 Unnamed: 24
0     top100_med_faminc_rank
1                        NaN
2                        NaN
3                        NaN
4                        NaN
...                      ...
6576                     NaN
6577                     NaN
6578                     NaN
6579                     NaN
6580                     NaN

[6581 rows x 25 columns]

In [5]:
cost_of_living.columns=cost_of_living.iloc[0]
#making row zero as the header
cost_of_living=cost_of_living[1:]
#Moving row 1 to row 0 and update the dataframe and the printing and reanalyzing the dataframe

# DIRECTION: removing columns and filtering for only the required columns in the next few lines

COL=cost_of_living.iloc[:,[1,3,12,13,14,15,16,17,18,19,20]].copy()
#Using DataFrame.iloc[] to create new DataFrame by df.copy() function. It copies all column numbers to a new dataframe.
COL
#COL is our new dataframe which contains only annual costs and not monthly costs

,State abv.,Family,Housing,Food,Transportation,Healthcare,Other Necessities,Childcare,Taxes,Total,median_family_income
1,TX,1p0c,8484,3014.58,10162.8,5389.48,4166.39,0,4687.84,35905.1,66485.1
2,TX,1p1c,11460,4442.76,10862.7,8138.65,5762.2,6947.8,4689.7,52303.8,66485.1
3,TX,1p2c,11460,6509.39,11661.9,10887.8,6511.02,11742.8,4363.63,63136.5,66485.1
4,TX,1p3c,15420,8683.81,12774.8,13637,8733.76,13218.2,5737.31,78204.8,66485.1
5,TX,1p4c,15420,10629.6,13129.5,16386.1,9438.79,13218.2,5405.7,83627.9,66485.1
...,...,...,...,...,...,...,...,...,...,...,...
6576,AZ,2p0c,8460,5173.73,12613.3,13480.8,4940.04,0,6468.11,51135.9,51688.4
6577,AZ,2p1c,11124,6439.23,13547.3,16847.6,6363.85,8299.39,8009.27,70630.6,51688.4
6578,AZ,2p2c,11124,8155.14,14254,20214.4,6985.59,15970.3,8670.22,85373.6,51688.4
6579,AZ,2p3c,15852,9956.81,15363.1,23581.2,9351.55,18330.5,10922.8,103358,51688.4
6580,AZ,2p4c,15852,12184.7,15637.1,26948,10158.8,18330.5,10746.2,109857,51688.4

In [6]:
COL1=COL[(COL.Family=='2p0c')]
#filtering for specifically my scenario i.e two person families with no children(yet)
COL1=COL1.iloc[:,[0,2,3,4,5,6,7,8,9,10]].copy()
COL1.isna()
COL2 = COL1.dropna(axis = 0, how = 'any',thresh = None, inplace = False )

In [7]:
COL2.columns=COL2.columns.str.replace(' ', '_')
COL2.columns=COL2.columns.str.replace('.','')
COL2
#changing column names to remove the spaces and other special characters from the column name
COL3=COL2.groupby('State_abv').apply(np.mean)
COL3
#grouping by state and getting average costs per state for all states

,Housing,Food,Transportation,Healthcare,Other_Necessities_,Childcare,Taxes,Total,median_family_income
State_abv,,,,,,,,,
AK,10752.000000,6081.178480,13352.177200,12112.760400,6099.324480,0.0,6564.793000,54962.234400,96782.462086
AL,7591.058824,6108.835016,12660.640447,11282.009315,4964.011828,0.0,7209.418179,49815.973835,65958.081158
AR,7393.090909,5569.877498,12586.262029,9567.842062,4696.994825,0.0,5635.324211,45449.391273,62468.672784
AZ,9841.714286,5881.070520,12702.983657,11567.316257,5696.985000,0.0,6709.152960,52399.223314,65623.797788
CA,16270.000000,6690.243268,13689.301464,10698.980592,8319.401712,0.0,8866.825892,64534.752720,85928.352671
CO,11992.500000,6494.106900,13259.963700,8311.760040,6698.426850,0.0,7510.323195,54267.080850,87001.280854
CT,13614.545455,6904.643291,12496.408036,10576.080687,7434.911247,0.0,8784.774502,59811.363382,103002.334898
DC,18576.000000,7079.940720,11135.583960,8930.852040,9296.159880,0.0,10155.714840,65174.250000,129045.452021
DE,10720.000000,6418.135240,12166.734080,10793.042200,6209.822160,0.0,7644.859360,53952.593600,81129.848178
FL,10816.137931,6530.016178,12222.913622,9935.123719,6285.195782,0.0,6043.099974,51832.487090,69566.458014
GA,8223.360000,5909.438213,12736.311787,10174.898563,5120.870107,0.0,6988.173691,49153.052784,64593.929319
HI,17910.000000,9476.460240,13234.918200,9232.760040,9923.194320,0.0,12444.081000,72221.413800,97963.088272
IA,7809.428571,5725.115031,12852.940714,9634.825749,4904.098920,0.0,6502.173180,47428.582371,83752.887279
ID,8072.400000,5912.084328,13295.320080,9813.665508,5067.130284,0.0,6213.959700,48374.559600,66861.356365
IL,8394.315789,5645.137743,12449.194371,11719.942680,5087.047768,0.0,7568.376815,50864.014421,78737.869502
IN,7848.000000,5438.136445,12451.331950,9799.532750,4814.091270,0.0,6258.272940,46609.365400,70651.530119
KS,8091.000000,5924.926335,12545.625480,11266.413090,5078.522910,0.0,6675.671355,49582.159350,77794.652422
KY,7605.818182,5352.541811,12893.530691,10713.204687,4695.324796,0.0,6995.442098,48255.862145,66345.344989
LA,8220.800000,6030.358912,12528.325760,11712.897240,5163.756848,0.0,6784.817136,50440.956480,62458.309068
MA,12802.500045,7103.330842,12298.127790,8319.129060,7212.667612,0.0,8231.927168,55967.681700,98039.954395
MD,9783.428571,6048.736817,13114.997091,7388.965749,5736.617846,0.0,6914.357983,48987.103714,80447.082797
ME,10989.000000,7407.265665,12754.672920,9618.079800,6665.692590,0.0,7551.573660,54986.284800,81288.591307
MI,8547.789474,5662.636345,12527.250322,8442.894758,5148.997756,0.0,6233.871543,46563.439642,74674.055402
MN,8536.615329,6347.925240,13017.426397,9030.589911,5393.256083,0.0,6406.322317,48732.135692,84281.771727
MO,6924.000000,5598.527820,12753.726912,10656.299784,4537.405752,0.0,5745.842976,46215.803640,65341.367319
MS,8029.200000,5871.235068,12741.843228,11414.959680,5036.675856,0.0,6635.990616,49729.904280,56579.141719
MT,8037.000000,6031.169190,13147.842600,9298.760040,5097.452580,0.0,6347.668980,47959.893600,68622.898260
NC,8804.275862,5787.665040,12687.169966,10648.219742,5287.235694,0.0,6971.876243,50186.442869,68220.523265
ND,7968.000000,6178.846200,13898.065600,8042.699760,5125.960200,0.0,5374.874880,46588.446400,76847.922119
NE,7064.571429,5643.821469,13291.965874,12256.414114,4604.751926,0.0,6321.234377,49182.758743,79772.501885
NH,12751.200000,6774.350088,12756.975840,7617.079800,7074.876864,0.0,6277.923576,53252.406000,106774.206524
NJ,15156.000000,6679.413708,11426.273460,9345.079800,7911.831540,0.0,7840.853484,58359.451560,97270.262619
NM,9024.000000,5870.188440,12296.776440,7210.760040,5396.751900,0.0,5399.119170,45197.596200,63496.601579
NV,10756.000000,6321.168960,12289.330760,9614.368680,6187.731920,0.0,5917.066400,51085.666800,75705.751041
NY,11844.000000,6286.959248,12060.427695,11308.748228,6569.561580,0.0,8323.902622,56393.599575,86554.998811
OH,7533.750000,5526.963210,12230.361967,9140.967577,4732.411492,0.0,5488.078777,44652.533250,71252.704109
OK,7279.200000,5818.479852,13126.870920,10712.747796,4745.805948,0.0,6490.964484,48174.069000,64637.552476
OR,11466.000000,6317.904915,13006.050300,9581.303865,6443.810190,0.0,9411.389730,56226.459150,74596.569381
PA,8864.000000,6042.797663,12532.806874,9166.244286,5401.320646,0.0,6701.470817,48708.640514,76094.819749
RI,12540.000000,7161.431040,12946.426800,7233.079800,7138.605420,0.0,7295.251860,54314.794800,108399.971964
SC,8714.250000,5654.950650,12602.830065,9833.755297,5206.528103,0.0,6229.411170,48241.725600,64316.527412
SD,8205.000000,5978.768490,12633.851430,14537.967630,5139.338730,0.0,6185.336100,52680.262800,76971.005236
TN,7497.000000,5962.595317,12866.412375,9895.590008,4876.942200,0.0,5151.469118,46250.008950,61584.401323
TX,9455.142857,5389.778357,12760.209311,10243.328183,5378.900414,0.0,5539.076094,48766.434886,70524.527806
UT,9578.000000,5861.063000,13363.164600,8491.008700,5594.181200,0.0,6646.050820,49533.468000,81015.019698
VA,9194.250000,6002.100420,13286.338425,10788.188475,5506.237073,0.0,7611.470542,52388.584350,77346.652121
VT,15180.000000,7217.074200,12960.134400,13473.080400,8115.343560,0.0,9687.656280,66633.286800,96636.117116
WA,11088.000000,6286.366392,13476.719680,8409.078008,6295.418088,0.0,5999.897432,51555.479440,79546.546615
WI,8261.250000,5719.804995,12676.796640,9936.658237,5065.887615,0.0,5823.877680,47484.275625,81697.463571
WV,7863.600000,5464.246260,12841.906536,16615.334400,4829.204268,0.0,8556.280092,56170.572240,66482.766821
WY,8598.000000,5972.614560,13125.515400,13732.760400,5279.508360,0.0,6224.388780,52932.788400,80795.807384

## Analsyis of Education System using AP score, Math and Language assesments and Graduation Rates

In [8]:
#Direction: AP data is being cleaned and prepared
AP=pd.read_excel("C:/Users/mayur/Downloads/school-report-of-ap-exams-grades-11-12-2021-2022.xls")
#loading excel file into dataframe
AP=AP.iloc[:,[0,1,2,3,4,5,9,10]].copy()
#copying columns needed and remvoing the rest using df.copy() and iloc method
index=("State","total_students","Total_ap_students_2021","Total_ap_students_2022","Total_ap_exams_2021","Total_ap_exams_2022","Exam_scores_above_3_2021","Exam_scores_above_3_2022")
#creating a list of the columns we need
AP.columns=index
#changing column names using df.columns() function and using index as a list of column names 
#Moving row 2 to row 0 and also removing extra lines that are not required (after 52) 
AP=AP[2:53].copy()
#resetting indexes and multiple transformations in the dataframe using reset index function of pandas
AP=AP.reset_index()
#Our original data did not have total grade 11 and 12 students in illinois
#Adding the number of grade 11 and grade 12 students in Illinois from 2021-2022 Illinois state board website
#https://www.isbe.net/pages/fall-enrollment-counts.aspx
AP['total_students'].values[13]=296360
#calculating participation percentage per state
part_pct=AP['Total_ap_students_2022']/AP['total_students']
AP['part_pct']=part_pct
#calculating rating for AP score based on particiaption rate and exam scores above 3 as criteria. 
#THis rating is used in rating colleges based on education
ap_score=(AP['Exam_scores_above_3_2022']*0.75)+(AP['part_pct']*0.25)
#creating a numpy array of ratings in order to normalize it using the preprocessing function
ap_arr = ap_score.values #returns a numpy array
#reshaping matrix into a 2D array using the reshape function from numpy
#min_max scaler does not work with 1 dimensional array
ap_matrix=ap_arr.reshape(-1,1)
#using min max scaler from scikit learn to normalize the ap ratings between 0 and 1
min_max_scaler = preprocessing.MinMaxScaler()
ap_scaled = min_max_scaler.fit_transform(ap_matrix)
#converting into dataframe to join it to the main AP dataframe
ap_score_scaled = pd.DataFrame(ap_scaled)
#adding the AP rating column and data to the main dataframe
AP["AP_rating"]=ap_score_scaled
apr=AP[['State','AP_rating']]
apr

                   State  AP_rating
0                Alabama   0.256684
1                 Alaska   0.522489
2                Arizona   0.610136
3               Arkansas   0.238022
4             California   0.812909
5               Colorado   0.811984
6            Connecticut   1.000000
7               Delaware   0.626183
8   District of Columbia   0.963035
9                Florida   0.720479
10               Georgia   0.840406
11                Hawaii   0.787067
12                 Idaho   0.639119
13              Illinois   0.823079
14               Indiana   0.553185
15                  Iowa   0.578576
16                Kansas   0.683991
17              Kentucky   0.516720
18             Louisiana   0.221002
19                 Maine   0.686247
20              Maryland   0.981971
21         Massachusetts   0.982138
22              Michigan   0.757755
23             Minnesota   0.838475
24           Mississippi   0.000000
25              Missouri   0.662819
26               Montana   0.748509
27              Nebraska   0.674348
28                Nevada   0.403056
29         New Hampshire   0.916248
30            New Jersey   0.949642
31            New Mexico   0.066772
32              New York   0.792896
33        North Carolina   0.692110
34          North Dakota   0.649159
35                  Ohio   0.805220
36              Oklahoma   0.316022
37                Oregon   0.665550
38          Pennsylvania   0.820681
39          Rhode Island   0.614919
40        South Carolina   0.790915
41          South Dakota   0.874401
42             Tennessee   0.660396
43                 Texas   0.491215
44                  Utah   0.893676
45               Vermont   0.774165
46              Virginia   0.837951
47            Washington   0.819133
48         West Virginia   0.219464
49             Wisconsin   0.885579
50               Wyoming   0.415395

In [9]:
#Direction: Math assesment and Reading assessment  and graduation rates dataset cleanup and ready for analysis

math_assess=pd.read_csv("C:/Users/mayur/Downloads/SPCsv202304075238.csv")
#loading math assesment data into df
index_1=('State','avg_score','diff_natl_avg','sig_symbol','pct_at_above_basic','pct_at_above_profcnt')
#renaming columns
math_assess.columns=index_1
#resetting index to initial indexes
math_assess=math_assess.reset_index()
#dropping unrequired columns i.e the index column and the symbol column which has no values.
math_assess=math_assess.drop(columns=['index','sig_symbol'])
#dropping puerto rico, DoDEA and National public row data
math_assess=math_assess.drop([0,29,53])
math_assess.sort_values('diff_natl_avg')
#resetting index to initial indexes
math_assess=math_assess.reset_index()
#dropping unrequired columns i.e the index column
math_assess=math_assess.drop(columns=['index'])
#converting the pct_at_above_profcnt to a float type so we can carry out numeric operations on that column
math_assess['pct_at_above_profcnt']=math_assess['pct_at_above_profcnt'].astype('float')
#calculating rating for math score based on pct of students above proficient and percentage above basic score.
math_assess['math_rating']=(math_assess['pct_at_above_basic']*0.004)+(math_assess['pct_at_above_profcnt']*0.006)
#creating a numpy array of ratings in order to normalize it using the preprocessing function
math_arr = math_assess['math_rating'].values #returns a numpy array
#reshaping matrix into a 2D array using the reshape function from nump
#min_max scaler does not work with 1 dimensional array
math_matrix=math_arr.reshape(-1,1)
#using min max scaler from scikit learn to normalize the ap ratings between 0 and 1
min_max_scaler = preprocessing.MinMaxScaler()
math_scaled = min_max_scaler.fit_transform(math_matrix)
#converting into dataframe to join it to the main math score dataframe
math_score_scaled = pd.DataFrame(math_scaled)
#adding the math rating column and data to the main dataframe
math_assess["math_rating"]=math_score_scaled
ma=math_assess[['State','math_rating']]
ma

                   State  math_rating
0                Wyoming     1.000000
1          Massachusetts     0.894309
2               Nebraska     0.910569
3                Florida     0.878049
4              Wisconsin     0.894309
5           North Dakota     0.853659
6                   Iowa     0.837398
7                   Utah     0.853659
8          New Hampshire     0.837398
9             New Jersey     0.764228
10               Indiana     0.804878
11             Minnesota     0.829268
12          South Dakota     0.837398
13                 Texas     0.756098
14               Montana     0.788618
15                  Ohio     0.772358
16          Pennsylvania     0.772358
17              Illinois     0.723577
18                Hawaii     0.715447
19              Virginia     0.707317
20           Connecticut     0.666667
21             Tennessee     0.674797
22                 Idaho     0.674797
23              Colorado     0.658537
24        North Carolina     0.634146
25                Kansas     0.634146
26            Washington     0.617886
27               Georgia     0.609756
28               Vermont     0.593496
29        South Carolina     0.593496
30          Rhode Island     0.593496
31              Kentucky     0.585366
32           Mississippi     0.544715
33                 Maine     0.560976
34              Missouri     0.560976
35              Michigan     0.495935
36               Arizona     0.479675
37            California     0.382114
38               Alabama     0.373984
39              Oklahoma     0.373984
40                Nevada     0.365854
41              Maryland     0.373984
42             Louisiana     0.341463
43                Oregon     0.341463
44              Arkansas     0.365854
45              New York     0.317073
46         West Virginia     0.211382
47                Alaska     0.300813
48              Delaware     0.235772
49  District of Columbia     0.073171
50            New Mexico     0.000000

In [10]:
#repeating above steps for reading data

read_assess=pd.read_csv("C:/Users/mayur/Downloads/SPCsv202304080200.csv")
index_2=('State','avg_score','diff_natl_avg','sig_symbol','pct_at_above_basic','pct_at_above_profcnt')
#renaming columns
read_assess.columns=index_1
#sorting values by differnce with national score, which is our criteria of judging a state's performance
read_assess.sort_values('diff_natl_avg')
#removed column 3 which had no relevant data
read_assess=read_assess.iloc[:,[0,1,2,4,5]]
#dropping puerto rico, DoDEA and National public row data
read_assess=read_assess.drop([0,27,53])
#resetting index to initial indexes
read_assess=read_assess.reset_index()
#dropping unrequired columns i.e the index column
read_assess=read_assess.drop(columns=['index'])
#converting the pct_at_above_profcnt to a float type so we can carry out numeric operations on that column
read_assess['pct_at_above_profcnt']=read_assess['pct_at_above_profcnt'].astype('float')
read_assess['pct_at_above_basic']=read_assess['pct_at_above_basic'].astype('float')
#calculating rating for reading score based on pct of students above proficient and percentage above basic score.
read_assess['read_rating']=(read_assess['pct_at_above_basic']*0.004)+(read_assess['pct_at_above_profcnt']*0.006)
#creating a numpy array of ratings in order to normalize it using the preprocessing function
read_arr = read_assess['read_rating'].values #returns a numpy array
#reshaping matrix into a 2D array using the reshape function from nump
read_matrix=read_arr.reshape(-1,1)
#using min max scaler from scikit learn to normalize the ap ratings between 0 and 1
min_max_scaler = preprocessing.MinMaxScaler()
read_scaled = min_max_scaler.fit_transform(read_matrix)
#converting into dataframe to join it to the main math score dataframe
read_score_scaled = pd.DataFrame(read_scaled)
#adding the math rating column and data to the main dataframe
read_assess["read_rating"]=read_score_scaled
ra=read_assess[['State','read_rating']]
ra

                   State  read_rating
0          Massachusetts     1.000000
1                Wyoming     0.881818
2                Florida     0.909091
3               Colorado     0.827273
4             New Jersey     0.809091
5          New Hampshire     0.781818
6                   Utah     0.781818
7            Connecticut     0.672727
8           Pennsylvania     0.645455
9                 Hawaii     0.672727
10               Montana     0.663636
11              Nebraska     0.663636
12                  Ohio     0.690909
13          South Dakota     0.609091
14                  Iowa     0.618182
15              Illinois     0.581818
16          North Dakota     0.581818
17             Wisconsin     0.600000
18               Indiana     0.600000
19          Rhode Island     0.609091
20           Mississippi     0.545455
21               Vermont     0.609091
22            Washington     0.590909
23              Kentucky     0.527273
24        South Carolina     0.536364
25        North Carolina     0.536364
26               Georgia     0.536364
27               Arizona     0.509091
28             Minnesota     0.536364
29                 Idaho     0.536364
30                Kansas     0.490909
31            California     0.454545
32                 Texas     0.427273
33              Virginia     0.518182
34             Tennessee     0.445455
35              New York     0.427273
36              Missouri     0.463636
37               Alabama     0.390909
38                 Maine     0.436364
39              Maryland     0.418182
40             Louisiana     0.354545
41              Arkansas     0.427273
42              Michigan     0.372727
43                Nevada     0.327273
44                Oregon     0.336364
45              Delaware     0.200000
46              Oklahoma     0.209091
47  District of Columbia     0.172727
48         West Virginia     0.100000
49                Alaska     0.136364
50            New Mexico     0.000000

In [11]:
#uploading Graduation rates data in a dataframe
grad_rate=pd.read_csv("C:/Users/mayur/Downloads/data.csv")
grad_rate=grad_rate.sort_values('HighSchool',ascending=False)
#copying columns needed and remvoing the rest using df.copy() and iloc method
index=("fips","State","densityMi","pop2023","pop2022","pop2020","pop2019","pop2010","growthRate","growth","growthSince2010","HighSchool")
#creating a list of the columns we need
grad_rate.columns=index
#changing column names using df.columns() function and using index as a list of column names
#converting the percentage values to decimals between 0 and 1
#these decimal values will be our graduation rating per state
grad_rate['HighSchool']=grad_rate['HighSchool']/100
#creating array of high shool grad rates in order to then normalize the values
grad_arr=grad_rate['HighSchool'].values
#reshaping matrix into a 2D array using the reshape function from nump
grad_matrix=grad_arr.reshape(-1,1)
#using minmaxscaler to scale the grad rate values
min_max_scaler=preprocessing.MinMaxScaler()
grad_scaled = min_max_scaler.fit_transform(grad_matrix)
#converting into dataframe to join it to the main math score dataframe
grad_score_scaled = pd.DataFrame(grad_scaled)
#adding the math rating column and data to the main dataframe
grad_rate["grad_rating"]=grad_score_scaled
gr=grad_rate[["State","grad_rating"]]
gr

                   State  grad_rating
0                Montana     1.000000
1                Wyoming     0.960396
2                Vermont     0.950495
3              Minnesota     0.940594
4          New Hampshire     0.930693
5                  Maine     0.920792
6                 Alaska     0.910891
7           North Dakota     0.910891
8                   Utah     0.900990
9              Wisconsin     0.861386
10                Hawaii     0.851485
11                  Iowa     0.851485
12          South Dakota     0.821782
13              Colorado     0.811881
14  District of Columbia     0.792079
15            Washington     0.772277
16              Nebraska     0.762376
17                Kansas     0.742574
18                 Idaho     0.732673
19              Michigan     0.732673
20         Massachusetts     0.712871
21                Oregon     0.712871
22          Pennsylvania     0.702970
23           Connecticut     0.693069
24                  Ohio     0.683168
27              Missouri     0.663366
25              Delaware     0.663366
26              Maryland     0.663366
28            New Jersey     0.633663
29              Virginia     0.633663
30              Illinois     0.574257
31               Indiana     0.534653
32          Rhode Island     0.524752
33              Oklahoma     0.465347
34               Florida     0.455446
35        North Carolina     0.455446
36        South Carolina     0.435644
37             Tennessee     0.425743
39               Georgia     0.396040
38               Arizona     0.396040
40         West Virginia     0.366337
41              Arkansas     0.326733
42              Kentucky     0.326733
43              New York     0.326733
44               Alabama     0.297030
45                Nevada     0.297030
46            New Mexico     0.257426
47             Louisiana     0.198020
48           Mississippi     0.138614
49                 Texas     0.049505
50            California     0.000000

In [12]:
#Giving a score to each state based on AP, math and reading asssesment and graduation rates
#The logic is 45% weightage to AP scores, 20% each to math and reading and 15% to graduation rate
#joining data frames to get a common dataframe that can be used for weightage based scoring
df1=pd.merge(apr,ra,how='outer',on='State')
df2=pd.merge(df1,ma,how='outer',on='State')
df3=pd.merge(df2,gr,how='outer',on='State')
df3['total_rating']=df3['AP_rating']*0.45+df3['read_rating']*0.2+df3['math_rating']*0.2+df3['grad_rating']*0.15
df3.sort_values(by=['total_rating'])

,State,AP_rating,read_rating,math_rating,grad_rating,total_rating
31,New Mexico,0.066772,0.000000,0.000000,0.257426,0.068661
48,West Virginia,0.219464,0.100000,0.211382,0.366337,0.215986
24,Mississippi,0.000000,0.545455,0.544715,0.138614,0.238826
18,Louisiana,0.221002,0.354545,0.341463,0.198020,0.268356
0,Alabama,0.256684,0.390909,0.373984,0.297030,0.313041
3,Arkansas,0.238022,0.427273,0.365854,0.326733,0.314745
36,Oklahoma,0.316022,0.209091,0.373984,0.465347,0.328627
28,Nevada,0.403056,0.327273,0.365854,0.297030,0.364555
1,Alaska,0.522489,0.136364,0.300813,0.910891,0.459189
43,Texas,0.491215,0.427273,0.756098,0.049505,0.465147
7,Delaware,0.626183,0.200000,0.235772,0.663366,0.468442
17,Kentucky,0.516720,0.527273,0.585366,0.326733,0.504062
2,Arizona,0.610136,0.509091,0.479675,0.396040,0.531720
4,California,0.812909,0.454545,0.382114,0.000000,0.533141
37,Oregon,0.665550,0.336364,0.341463,0.712871,0.541994
32,New York,0.792896,0.427273,0.317073,0.326733,0.554682
42,Tennessee,0.660396,0.445455,0.674797,0.425743,0.585090
39,Rhode Island,0.614919,0.609091,0.593496,0.524752,0.595944
8,District of Columbia,0.963035,0.172727,0.073171,0.792079,0.601357
25,Missouri,0.662819,0.463636,0.560976,0.663366,0.602696
14,Indiana,0.553185,0.600000,0.804878,0.534653,0.610107
33,North Carolina,0.692110,0.536364,0.634146,0.455446,0.613868
22,Michigan,0.757755,0.372727,0.495935,0.732673,0.624623
12,Idaho,0.639119,0.536364,0.674797,0.732673,0.639737
16,Kansas,0.683991,0.490909,0.634146,0.742574,0.644193
19,Maine,0.686247,0.436364,0.560976,0.920792,0.646398
40,South Carolina,0.790915,0.536364,0.593496,0.435644,0.647230
10,Georgia,0.840406,0.536364,0.609756,0.396040,0.666813
15,Iowa,0.578576,0.618182,0.837398,0.851485,0.679198
20,Maryland,0.981971,0.418182,0.373984,0.663366,0.699825
50,Wyoming,0.415395,0.881818,1.000000,0.960396,0.707351
34,North Dakota,0.649159,0.581818,0.853659,0.910891,0.715851
46,Virginia,0.837951,0.518182,0.707317,0.633663,0.717227
13,Illinois,0.823079,0.581818,0.723577,0.574257,0.717603
47,Washington,0.819133,0.590909,0.617886,0.772277,0.726210
45,Vermont,0.774165,0.609091,0.593496,0.950495,0.731466
27,Nebraska,0.674348,0.663636,0.910569,0.762376,0.732654
9,Florida,0.720479,0.909091,0.878049,0.455446,0.749960
35,Ohio,0.805220,0.690909,0.772358,0.683168,0.757478
38,Pennsylvania,0.820681,0.645455,0.772358,0.702970,0.758315
11,Hawaii,0.787067,0.672727,0.715447,0.851485,0.759538
26,Montana,0.748509,0.663636,0.788618,1.000000,0.777280
5,Colorado,0.811984,0.827273,0.658537,0.811881,0.784337
23,Minnesota,0.838475,0.536364,0.829268,0.940594,0.791529
41,South Dakota,0.874401,0.609091,0.837398,0.821782,0.806046
6,Connecticut,1.000000,0.672727,0.666667,0.693069,0.821839
49,Wisconsin,0.885579,0.600000,0.894309,0.861386,0.826580
30,New Jersey,0.949642,0.809091,0.764228,0.633663,0.837052
44,Utah,0.893676,0.781818,0.853659,0.900990,0.864398
29,New Hampshire,0.916248,0.781818,0.837398,0.930693,0.875759
21,Massachusetts,0.982138,1.000000,0.894309,0.712871,0.927754

## Crime Data Analysis

In [13]:
crime_rating=pd.read_csv("C:/Users/mayur/Downloads/crime_data.csv")

crime_rating

,fips,state,densityMi,pop2023,pop2022,pop2020,pop2019,pop2010,growthRate,growth,growthSince2010,reported,rate,violent,violentRate,nonViolent,nonViolentRate
0,11,District of Columbia,11062.54098,674815,671803,670868,663953.5,601723,0.00448,3012,0.12147,14113,7985.932,7127,999.837,49798,6986.095
1,35,New Mexico,17.39527,2110011,2113344,2118390,2112468.9,2059179,-0.00158,-3333,0.02469,22077,6462.032,16393,778.277,119718,5683.754
2,22,Louisiana,105.39265,4553384,4590241,4651664,4639834.8,4533372,-0.00803,-36857,0.00441,35473,6408.216,29704,639.440,267978,5768.776
3,8,Colorado,56.62333,5868555,5839926,5784865,5709298.1,5029196,0.00490,28629,0.16690,30238,6090.756,24570,423.058,329164,5667.698
4,45,South Carolina,178.70337,5372002,5282634,5131848,5081199.6,4625364,0.01692,89368,0.16142,33133,5972.837,27691,530.678,283974,5442.158
5,5,Arkansas,58.86715,3063152,3045637,3014195,3004367.3,2915918,0.00575,17515,0.05049,25590,5898.753,20363,671.930,158400,5226.822
6,40,Oklahoma,59.01851,4048375,4019800,3964912,3943555.9,3751351,0.00711,28575,0.07918,23666,5869.825,18255,458.578,215410,5411.247
7,53,Washington,117.83476,7830827,7785786,7724031,7624081.9,6724540,0.00579,45041,0.16451,28061,5758.570,22596,293.698,420446,5464.871
8,47,Tennessee,173.01630,7134327,7051339,6925619,6867667.6,6346105,0.01177,82988,0.12421,51314,5658.304,46328,672.704,343350,4985.600
9,41,Oregon,44.00522,4223973,4240137,4244795,4203422.9,3831074,-0.00381,-16164,0.10256,17698,5609.893,12380,291.877,225564,5318.016
10,29,Missouri,89.98998,6186091,6177957,6153998,6137490.9,5988927,0.00132,8134,0.03292,38447,5604.784,33385,542.709,311396,5062.075
11,2,Alaska,1.28449,732984,733583,732923,730653.8,710231,-0.00082,-599,0.03204,10647,5358.896,6126,837.849,33056,4521.047
12,49,Utah,41.65130,3422487,3380800,3283785,3231795.0,2763885,0.01233,41687,0.23829,13400,5189.516,8471,260.656,160182,4928.860
13,15,Hawaii,223.14152,1433238,1440196,1451043,1441968.8,1360301,-0.00483,-6958,0.05362,8399,5076.880,3576,254.157,67856,4822.723
14,4,Arizona,65.61541,7453517,7359197,7179943,7101150.4,6392017,0.01282,94320,0.16607,40435,4940.118,35980,484.814,330646,4455.304
15,48,Texas,116.75553,30500280,30029572,29232474,28823782.7,25145561,0.01567,470708,0.21295,135574,4936.535,131084,446.460,1318320,4490.075
16,37,North Carolina,222.79940,10832061,10698973,10449445,10358048.8,9535483,0.01244,133088,0.13597,48904,4872.292,44451,419.317,472052,4452.975
17,20,Kansas,35.91504,2936378,2937150,2937919,2929438.9,2853118,-0.00026,-772,0.02918,16783,4823.212,12385,425.046,128154,4398.167
18,1,Alabama,100.67620,5098746,5074296,5031362,5006199.4,4779736,0.00482,24450,0.06674,26596,4727.065,22322,453.558,210322,4273.507
19,6,California,249.81347,38915693,39029342,39501653,39276883.3,37253956,-0.00291,-113649,0.04461,178304,4719.900,174026,442.049,1684108,4277.852
20,30,Montana,7.82919,1139507,1122867,1087075,1077309.0,989415,0.01482,16640,0.15170,9319,4711.464,5077,469.842,45834,4241.623
21,38,North Dakota,11.31271,780588,779261,779518,768825.3,672591,0.00170,1327,0.16057,6766,4577.236,2518,329.017,32512,4248.219
22,27,Minnesota,71.87131,5722897,5717184,5709852,5669259.3,5303925,0.00100,5713,0.07899,19948,4527.250,15698,277.480,240424,4249.770
23,28,Mississippi,62.45398,2930528,2940057,2958141,2959056.6,2967297,-0.00324,-9529,-0.01239,12841,4494.426,8638,291.157,124702,4203.269
24,46,South Dakota,12.18140,923484,909824,887799,880437.1,814180,0.01501,13660,0.13425,8389,4414.837,4476,501.391,34936,3913.446
25,13,Georgia,191.91701,11037723,10912876,10729828,10625610.5,9687653,0.01144,124847,0.13936,46865,4414.802,42850,400.093,429976,4014.709
26,10,Delaware,529.49461,1031985,1018396,992114,982696.0,897934,0.01334,13589,0.14929,8185,4354.642,4262,431.897,38710,3922.745
27,32,Nevada,29.23222,3209142,3177772,3115648,3074138.3,2700551,0.00987,31370,0.18833,18298,4313.506,14445,460.287,120924,3853.219
28,31,Nebraska,25.67286,1972292,1967923,1962642,1949011.9,1826341,0.00222,4369,0.07991,10291,4152.405,6473,334.081,73982,3818.323
29,39,Ohio,287.50579,11747774,11756058,11797517,11771415.7,11536504,-0.00070,-8284,0.01831,39805,4009.418,36104,308.760,432726,3700.658
30,18,Indiana,191.27287,6852542,6833037,6788799,6758299.3,6483802,0.00285,19505,0.05687,27727,3924.039,24161,357.678,240906,3566.361
31,12,Florida,422.59351,22661577,22244823,21589602,21310772.8,18801310,0.01873,416754,0.20532,86907,3922.458,83368,383.595,769112,3538.862
32,21,Kentucky,114.42109,4518031,4512310,4507445,4490637.2,4339367,0.00127,5721,0.04117,15159,3818.102,11600,259.088,159346,3559.014
33,19,Iowa,57.34903,3203345,3200517,3190571,3176149.4,3046355,0.00088,2828,0.05153,12997,3699.976,9601,303.487,107450,3396.489
34,42,Pennsylvania,289.02749,12931957,12972008,12994440,12965233.9,12702379,-0.00309,-40051,0.01807,53081,3677.679,49793,389.517,420334,3288.161
35,24,Maryland,634.04862,6154710,6164660,6173205,6133239.7,5773552,-0.00161,-9950,0.06602,27435,3619.488,24215,399.864,194974,3219.623
36,17,Illinois,224.74459,12477595,12582032,12786580,12790985.2,12830632,-0.00830,-104437,-0.02752,56731,3544.667,53612,425.914,392574,3118.753
37,56,Wyoming,6.00743,583279,581381,577605,576207.1,563626,0.00326,1898,0.03487,4585,3455.441,1364,234.232,18758,3221.209
38,9,Connecticut,749.49504,3629055,3626205,3597362,3595035.5,3574097,0.00079,2850,0.01538,9589,3311.746,6459,181.585,111340,3130.161
39,55,Wisconsin,109.03241,5904977,5892539,5896271,5875342.5,5686986,0.00211,12438,0.03833,21832,3294.709,18861,323.369,173308,2971.340
40,26,Michigan,177.41244,10030722,10034113,10069577,10050983.3,9883640,-0.00034,-3391,0.01488,50363,3199.772,47641,478.009,271266,2721.763
41,36,New York,413.71663,19496810,19677151,20108296,20035276.6,19378102,-0.00916,-180341,0.00613,73160,3185.200,70339,363.758,545576,2821.442
42,54,West Virginia,73.41651,1764786,1775156,1791420,1797577.4,1852994,-0.00584,-10370,-0.04760,9151,3154.662,6352,355.897,49952,2798.765
43,51,Virginia,220.55895,8709873,8683619,8636471,8572926.3,8001024,0.00302,26254,0.08859,20838,3121.483,17925,208.659,250228,2912.824
44,44,Rhode Island,1054.62573,1090483,1093734,1096345,1091967.2,1052567,-0.00297,-3251,0.03602,4931,2721.722,2440,230.815,26332,2490.907
45,50,Vermont,70.21330,647156,647064,642893,641177.8,625741,0.00014,92,0.03422,3515,2607.376,1081,173.419,15172,2433.957
46,34,New Jersey,1258.55820,9255437,9261699,9271689,9223709.5,8791894,-0.00068,-6262,0.05272,19669,2511.751,17353,195.365,205750,2316.386
47,16,Idaho,23.88287,1973752,1939033,1849202,1821040.0,1567582,0.01791,34719,0.25911,6656,2466.346,4432,242.595,40626,2223.751
48,23,Maine,45.17855,1393442,1385340,1363557,1360037.4,1328361,0.00585,8102,0.04899,3778,2420.932,1466,108.581,31220,2312.351
49,25,Massachusetts,894.13564,6974258,6981974,6995729,6950919.0,6547629,-0.00111,-7716,0.06516,23394,2415.177,21288,308.809,145204,2106.367
50,33,New Hampshire,156.70245,1402957,1395231,1378587,1372375.3,1316470,0.00554,7726,0.06570,4198,2344.184,2000,146.383,30028,2197.801

## Healthcare Analysis based on per capita spend

In [22]:
healthcare_cost=pd.read_csv("C:/Users/mayur/Downloads/healthcare_expenditure_data.csv")

#creating array of healthcare cost in order to then normalize the values
healthcare_arr=healthcare_cost['spentPerCapita'].values
#reshaping matrix into a 2D array using the reshape function from nump
healthcare_matrix=healthcare_arr.reshape(-1,1)
#using min max scaler from scikit learn to normalize the healthcare ratings between 0 and 1
min_max_scaler = preprocessing.MinMaxScaler()
healthcare_matrix = min_max_scaler.fit_transform(healthcare_matrix)
#converting into dataframe to join it to the main math score dataframe
healthcare_cost_scaled=pd.DataFrame(healthcare_matrix)
healthcare_cost['healthcare_rating']=healthcare_cost_scaled
healthcare_rating=healthcare_cost[['state','healthcare_rating']]
healthcare_rating
#healthcare_rating

                   state  healthcare_rating
0   District of Columbia           1.000000
1                 Alaska           0.852399
2          Massachusetts           0.767695
3               Delaware           0.716538
4                Vermont           0.705803
5            Connecticut           0.650285
6           North Dakota           0.648943
7               New York           0.636699
8          New Hampshire           0.604998
9           Rhode Island           0.598625
10                 Maine           0.595270
11         West Virginia           0.583697
12          Pennsylvania           0.549480
13          South Dakota           0.494968
14             Minnesota           0.484569
15            New Jersey           0.482556
16                  Ohio           0.457900
17             Wisconsin           0.456223
18              Maryland           0.439450
19              Nebraska           0.407581
20               Wyoming           0.392150
21               Indiana           0.388796
22              Illinois           0.382422
23               Montana           0.375545
24                  Iowa           0.372023
25              Missouri           0.356424
26               Florida           0.351224
27              Michigan           0.347702
28                Oregon           0.345857
29              Kentucky           0.339148
30            Washington           0.323885
31             Louisiana           0.307447
32                Kansas           0.279940
33           Mississippi           0.279101
34              Oklahoma           0.275914
35              Virginia           0.264005
36            California           0.262831
37              Arkansas           0.239181
38             Tennessee           0.233143
39        South Carolina           0.222912
40                Hawaii           0.220899
41               Alabama           0.217880
42        North Carolina           0.215029
43            New Mexico           0.206642
44                 Texas           0.170413
45                 Idaho           0.158504
46              Colorado           0.137873
47                Nevada           0.122778
48               Georgia           0.101476
49               Arizona           0.078833
50                  Utah           0.000000